// Place here Action types constants

export const SET_BASE_PRIMARY_TYPE = 'SET_BASE_PRIMARY_TYPE'
export const SET_BASE_SECONDARY_TYPE = 'SET_BASE_SECONDARY_TYPE'
export const SET_BASE_PRIMARY_VALUE = 'SET_BASE_PRIMARY_VALUE'
export const UPDATE_BASE_PRIMARY_VALUE = 'UPDATE_BASE_PRIMARY_VALUE'
export const SET_BASE_SECONDARY_VALUE = 'SET_BASE_SECONDARY_VALUE'
export const SWAP_BASE_VALUES = 'SWAP_BASE_VALUES'
export const UPDATE_BASE_SECONDARY_VALUE = 'UPDATE_BASE_SECONDARY_VALUE'
export const UPDATE_DATA_LIST_VALUES = 'SET_DATA_LIST_VALUES'
export const SET_LOCALE = 'SET_LOCALE'
export const GET_CURRENCIES_LIST = 'GET_CURRENCIES_LIST'
export const CACHE_ALL_DATA_LIST = 'CACHE_CURRENCIES_LIST'
