export default {
  page_content_title: 'Currency Converter',
  footer: 'Footer',
  headerVersion: 'Version 1.0',
  headerAuthor: 'by Egor Malishevski',
  header: 'Initial Application',
  convert_block_input_placeholder: 'Value',
  convert_block_select_placeholder: 'Search',
  button_cache_text: 'Save to cache',
  access_denied: 'You have no access to open this page',
  return_home: 'Return Home',
  page_not_found: 'Requested page is not found',
  update_cache_success_text: 'Cache has been updated',
  alert_success_text: 'Success',
  alert_info_text: 'Info',
  alert_warning_text: 'Warning',
  alert_error_text: 'Error',
  sign_out_text: 'Log out',
  sign_up_title: 'Sign Up',
  sign_in_title: 'Sign In',
  signup_swap_text: 'Already have an account?',
  signin_swap_text: 'Don\'t have an account yet?',
  signup_firstName_placeholder: 'First Name',
  signup_lastName_placeholder: 'Last name',
  login_email_placeholder: 'Email',
  login_password_placeholder: 'Password',
  signup_confirm_placeholder: 'Confirm password',
  signup_btn_text: 'Sign Up',
  signup_swap_btn_text: 'Create an account',
  signin_btn_text: 'Login',
  header_converter_link: 'Converter',
  header_map_link: 'Map',
}
