export default {
  converter_page_title: 'Конвертер валют',
  map_page_title: 'Карта мира',
  footer: 'Подвал',
  headerVersion: 'Версия 1.0',
  headerAuthor: 'Автор: Егор Малишевский',
  header: 'Базовое приложение',
  convert_block_input_placeholder: 'Значение',
  convert_block_select_placeholder: 'Поиск',
  button_cache_text: 'Сохранить в кэш',
  access_denied: 'Для доступа к этой странице необходимо авторизоваться',
  return_home: 'Вернуться на главную страницу',
  page_not_found: 'Страница не найдена',
  alert_success_text: 'Успешно',
  alert_info_text: 'Информация',
  alert_warning_text: 'Предупреждение',
  alert_error_text: 'Ошибка',
  sign_out_text: 'Выход',
  sign_up_title: 'Регистрация',
  sign_in_title: 'Авторизация',
  update_cache_success_text: 'Кэш был обновлен',
  signup_swap_text: 'Уже есть аккаунт?',
  signin_swap_text: 'Нет аккаунта?',
  signup_firstName_placeholder: 'Имя',
  signup_lastName_placeholder: 'Фамилия',
  login_email_placeholder: 'Почта',
  login_password_placeholder: 'Пароль',
  signup_confirm_placeholder: 'Повтор пароля',
  signup_btn_text: 'Зарегистрироваться',
  signup_swap_btn_text: 'Создать аккаунт',
  signin_btn_text: 'Войти',
  header_converter_link: 'Конвертер',
  header_map_link: 'Карта',
}
